apiVersion: v1
kind: ServiceAccount
metadata:
  name: scmigrate
  namespace: scmigrate-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scmigrate
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes", "pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scmigrate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scmigrate
subjects:
  - kind: ServiceAccount
    name: scmigrate
    namespace: scmigrate-system
